[package]
name = "app"
version = "0.0.0"
edition = "2024"

[dependencies]
metw-server = { workspace = true }

tokio = { workspace = true, features = ["net", "rt", "rt-multi-thread"] }
tower-http = { workspace = true, features = ["cors", "trace"] }
axum = { workspace = true, features = ["macros"] }

tower_governor = { version = "0.8", default-features = false, features = ["axum"] }
governor = "0.10"

utoipa = { workspace = true, features = ["axum_extras"] }

tracing = { workspace = true }

thiserror = { workspace = true }
dotenvy = { workspace = true }

serde = { workspace = true, features = ["derive"] }
base64 = { workspace = true }

state = { path = "../state/" }
service = { path = "../service/", features = ["email-templates"] }

[features]
transparent-errors = []
otel = ["metw-server/otel"]
allow-all-cors = ["metw-server/allow-all-cors"]

[lints]
workspace = true
