[package]
name = "app"
version = "0.0.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["net", "rt", "rt-multi-thread"] }
tower-http = { workspace = true, features = ["cors", "trace"] }
axum = { workspace = true, features = ["macros"] }

tower_governor = { version = "0.8", default-features = false, features = ["axum"] }
governor = "0.10"

utoipa = { workspace = true, features = ["axum_extras"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-opentelemetry = { version = "0.33", optional = true }
opentelemetry = { version = "0.32", optional = true }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"], optional = true }
opentelemetry_sdk = { version = "0.32", optional = true }

thiserror = { workspace = true }
dotenvy = { workspace = true }

serde = { workspace = true, features = ["derive"] }

state = { path = "../state/" }
service = { path = "../service/" }

[features]
transparent-errors = []
otel = ["dep:opentelemetry", "dep:tracing-opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry_sdk"]

[lints]
workspace = true
