use chrono::{NaiveDate, NaiveDateTime, NaiveTime, Utc};
use serde::{Deserialize, Serialize};
use std::{
    sync::{LazyLock, Mutex},
    time::Duration,
};

macro_rules! id_newtype {
    ($name:ident) => { pastey::paste! {
        #[doc = "Unique "]
        #[doc = stringify!($name)]
        #[doc = " identifier."]
        #[derive(Debug, Serialize, Deserialize, Clone, Copy, Default, Hash, PartialEq, Eq)]
        pub struct [< $name Id >](i64);

        impl std::fmt::Display for [< $name Id >] {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                self.0.fmt(f)
            }
        }

        impl From<[< $name Id >]> for i64 {
            fn from(value: [< $name Id >]) -> Self {
                value.0
            }
        }

        /// Creates an ID from an arbitrary integer.
        ///
        /// Only available in test and testutil builds. Production code must
        /// use [`Self::unique`] to obtain IDs generated by the snowflake
        /// algorithm.
        #[cfg(any(feature = "testutil", test))]
        impl From<i64> for [< $name Id >] {
            fn from(value: i64) -> Self {
                [< $name Id >](value)
            }
        }

        // sqlx integrations
        impl sqlx::Type<sqlx::Postgres> for [< $name Id >] {
            fn type_info() -> sqlx::postgres::PgTypeInfo {
                <i64 as sqlx::Type<sqlx::Postgres>>::type_info()
            }
        }

        impl<'q> sqlx::Encode<'q, sqlx::Postgres> for [< $name Id >] {
            fn encode_by_ref(
                &self,
                buf: &mut sqlx::postgres::PgArgumentBuffer,
            ) -> Result<sqlx::encode::IsNull, sqlx::error::BoxDynError> {
                sqlx::Encode::<'q, sqlx::Postgres>::encode_by_ref(&self.0, buf)
            }
        }

        impl<'r> sqlx::Decode<'r, sqlx::Postgres> for [< $name Id >] {
            fn decode(
                value: sqlx::postgres::PgValueRef<'r>,
            ) -> Result<Self, sqlx::error::BoxDynError> {
                Ok([< $name Id >](<i64 as sqlx::Decode<sqlx::Postgres>>::decode(value)?))
            }
        }

        impl [< $name Id >] {
            /// Generates a new unique ID using the snowflake algorithm.
            pub fn unique() -> Self {
                [< $name Id >](internal_snowflake())
            }
        }
    } };
}

id_newtype!(Account);

/// Year zero of metw.cc.
///
/// 2022 Aug 12, 00:00:00 (`1660262400000`)
pub static EPOCH: LazyLock<u64> = LazyLock::new(|| {
    NaiveDateTime::new(
        NaiveDate::from_ymd_opt(2022, 8, 12).unwrap(),
        NaiveTime::from_hms_opt(0, 0, 0).unwrap(),
    )
    .and_utc()
    .timestamp_millis() as u64
});

#[cfg(test)]
static INCREMENT_MAX: i64 = 2i64.pow(4);
#[cfg(not(test))]
static INCREMENT_MAX: i64 = 2i64.pow(12);

struct SnowflakeState {
    last_overflow: i64,
    increment: i64,
}

static GLOBAL_STATE: Mutex<SnowflakeState> = Mutex::new(SnowflakeState {
    last_overflow: 0,
    increment: 0,
});

/// ID generator inspired from Twitter's snowflake format. Available only in
/// `cfg(test)` or `feature = "testutil"`.
///
/// | Field | Bits | Description |
/// | -- | -- | -- |
/// | Timestamp | 22 to 63 | Milliseconds since metw.cc [`EPOCH`] |
/// | Reserved for future use | 12 to 21 | |
/// | Increment | 0 to 11 | For every ID that is generated, this number is incremented |
#[cfg(any(feature = "testutil", test))]
pub fn snowflake() -> i64 {
    internal_snowflake()
}

fn internal_snowflake() -> i64 {
    let timestamp = Utc::now().timestamp_millis() - *EPOCH as i64;

    // Ensure the time is not yet May 15 2109 07:35:11
    assert!(timestamp < 2i64.pow(42) - 1);

    let mut state = GLOBAL_STATE.lock().unwrap();

    if state.last_overflow == timestamp {
        drop(state);

        std::thread::sleep(Duration::from_millis(1));
        return internal_snowflake();
    }

    if state.increment == 0 {
        state.last_overflow = timestamp;
    }

    state.increment += 1;

    if state.increment == INCREMENT_MAX {
        state.increment = 0;
    }

    (timestamp << 22) | state.increment
}

#[cfg(test)]
#[test]
#[serial_test::serial]
fn test_snowflake() {
    use std::collections::HashSet;

    let cap = 2usize.pow(12);
    let mut snowflakes = HashSet::with_capacity(cap);

    for _ in 0..cap {
        let snowflake = snowflake();

        assert!(!snowflakes.contains(&snowflake));

        snowflakes.insert(snowflake);
    }
}
